name: control_gastos_tarjetas
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  dio: ^5.4.3+1
  flutter:
    sdk: flutter
  flutter_datetime_picker_plus: ^2.2.0
  flutter_flip_card: ^0.0.6
  flutter_html: ^3.0.0-beta.2
  flutter_masked_text2: ^0.9.1
  gap: ^3.0.1
  get: ^4.6.6
  intl: ^0.19.0
  json_annotation: ^4.9.0
  loading_animation_widget: ^1.2.1
  logger: ^2.3.0
  lottie: ^3.1.2
  molten_navigationbar_flutter: ^1.0.1
  shared_preferences: ^2.2.3
  smooth_page_indicator: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  json_serializable: ^6.8.0
  build_runner: ^2.4.9

flutter:
  uses-material-design: true

  assets:
    - env/
    - assets/animations/
    - assets/images/
